name: Issue Close Check
description: Auto add reviewers for a pull request which associate a special issue
author: guguducken

inputs:
  token_action:
    description: "The user GitHub token for get data"
    required: true
  id_label:
    description: "The id of label which in issue"
    default: ""
    required: true
  uri_notice:
    description: "The webhook uri which should send message to"
    default: ""
    required: true
  mentions:
    description: "the mentions"
    required: false

runs:
  using: "node16"
  main: "src/index.js"
branding:
  icon: "arrow-down"
  color: "blue"
